services:
  headscale:
    image: 'headscale/headscale:latest'
    container_name: 'headscale'
    restart: 'unless-stopped'
    command: 'serve'
    ports:
      - "3478:3478"
    volumes:
      - './data:/var/lib/headscale'
      - './configs/headscale:/etc/headscale'
    environment:
      TZ: 'America/Edmonton'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.headscale.rule=Host(`tailscale.moosergamer.xyz`) && PathPrefix(`/api`)"
      - "traefik.http.routers.headscale.entrypoints=websecure"
      - "traefik.http.routers.headscale.tls=true"
      - "traefik.http.routers.headscale.tls.certresolver=myresolver"
      - "traefik.http.services.headscale.loadbalancer.server.port=8080"

  headplane:
    container_name: headplane
    image: ghcr.io/tale/headplane:latest
    restart: unless-stopped
    volumes:
      - './data:/var/lib/headscale'
      - './configs/headscale:/etc/headscale'
      - './configs/headplane:/etc/headplane'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    environment:
      COOKIE_SECRET: 'abcdefghijklmnopqrstuvwxyz'
      HEADSCALE_INTEGRATION: 'docker'
      HEADSCALE_CONTAINER: 'headscale'
      DISABLE_API_KEY_LOGIN: 'false'
      HOST: '0.0.0.0'
      PORT: '3000'
      COOKIE_SECURE: 'true'
      # ADD THIS LINE - Headscale API URL
      HEADSCALE_URL: 'http://headscale:8080'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.headplane.rule=Host(`tailscale.moosergamer.xyz`)"
      - "traefik.http.routers.headplane.entrypoints=websecure"
      - "traefik.http.routers.headplane.tls=true"
      - "traefik.http.routers.headplane.tls.certresolver=myresolver"
      - "traefik.http.services.headplane.loadbalancer.server.port=3000"

  traefik:
    image: "traefik:v3.3"
    container_name: "traefik"
    restart: 'unless-stopped'
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      # CHANGE TO PRODUCTION SERVER:
      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
      # UPDATE WITH YOUR REAL EMAIL:
      - "--certificatesresolvers.myresolver.acme.email=your-real-email@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"